import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/providers/tanstack-provider";
import ReduxProvider from "@/providers/redux-provider";
import { Toaster } from "sonner";
import Guard from "@/providers/guard";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-tahoma antialiased`} suppressHydrationWarning>
        <Guard>
          <ReduxProvider>
            <TanstackProvider>
              <Toaster />
              {children}
            </TanstackProvider>
          </ReduxProvider>
        </Guard>
      </body>
    </html>
  );
}
