export const urls = {
  detailsByChassisNo: (chassisNo: string) => `/cars/${chassisNo}/details`,
  transactions: {
    list: "/transactions",
    byChassisNo: (chassisNo: string) => `/transactions/${chassisNo}`,
    create: "/transactions",
  },
  cheques: {
    list: "/cheques",
    byChassisNo: (chassisNo: string) => `/cheques/${chassisNo}`,
    unpaid: (chassisNo: string) => `/cheques/unpaid/${chassisNo}`,
    create: "/cheques",
  },
  investmentByChassis: (chassisNo: string) =>
    `/transactions/investment/${chassisNo}`,
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
  },
  settings: {
    list: "/settings",
  },
  // New API endpoints
  deals: {
    list: "/deals",
    byId: (id: string) => `/deals/byId/${id}`,
    byVin: (vin: string) => `/deals/byVin/${vin}`,
    byVehicleId: (vehicleId: string) => `/deals/byVehicleId/${vehicleId}`,
    byPerson: (personId: string) => `/deals/byPersonId/${personId}`,
    byStatus: (status: string) => `/deals/byStatus/${status}`,
    create: "/deals",
    update: (id: string) => `/deals/byId/${id}`,
    delete: (id: string) => `/deals/byId/${id}`,
    option: (dealId: string, optionId: string) =>
      `/deals/${dealId}/byOptionId/${optionId}`,
  },
  transactionsNew: {
    list: "/transactions",
    byId: (id: string) => `/transactions/byId/${id}`,
    byDeal: (dealId: string) => `/transactions/byDealId/${dealId}`,
    byPerson: (personId: string) => `/transactions/byPersonId/${personId}`,
    byProvider: (providerId: string) => `/transactions/byPerson/${providerId}`,
    byAccount: (accountId: string) => `/transactions/byAccountId/${accountId}`,
    byType: (type: string) => `/transactions/byType/${type}`,
    byDateRange: "/transactions/byDateRange",
    create: "/transactions",
    update: (id: string) => `/transactions/byId/${id}`,
    delete: (id: string) => `/transactions/byId/${id}`,
  },
  chequesNew: {
    list: "/cheques",
    byVin: (vin: string) => `/cheques/byVin/${vin}`,
    byId: (id: string) => `/cheques/byId/${id}`,
    byDeal: (dealId: string) => `/cheques/byDealId/${dealId}`,
    byPerson: (personId: string) => `/cheques/byPersonId/${personId}`,
    byStatus: (status: string) => `/cheques/byStatus/${status}`,
    unpaidByDeal: (dealId: string) => `/cheques/unpaid/byDealId/${dealId}`,
    create: "/cheques",
    update: (id: string) => `/cheques/byId/${id}`,
    addAction: (id: string) => `/cheques/byId/${id}/action`,
    delete: (id: string) => `/cheques/byId/${id}`,
  },
  people: {
    list: "/people",
    byId: (id: string) => `/people/byId/${id}`,
    byNationalId: (nationalId: string) => `/people/byNationalId/${nationalId}`,
    byRole: (role: string) => `/people/role/${role}`,
    search: (name: string) => `/people/search/${name}`,
    create: "/people",
    update: (id: string) => `/people/byId/${id}`,
    updateWallet: (id: string) => `/people/byId/${id}/wallet`,
    deleteWalletTransaction: (id: string) => `/people/byId/${id}/wallet/delete`,
    delete: (id: string) => `/people/byId/${id}`,
  },
  wallet: {
    updateWalletTransfer: "/wallet/update-wallet-transfer",
  },
  report: {
    generatePersonReport: "/exportToExcel/generate-person-report",
  },
  users: {
    list: "/users",
  },
  vehicles: {
    list: "/vehicles",
    byId: (id: string) => `/vehicles/byId/${id}`,
    byVin: (vin: string) => `/vehicles/byVin/${vin}`,
    create: "/vehicles",
    update: (id: string) => `/vehicles/byId/${id}`,
    delete: (id: string) => `/vehicles/byId/${id}`,
  },
  businessAccounts: {
    list: "/business-accounts",
    active: "/business-accounts/active",
    byId: (id: string) => `/business-accounts/byId/${id}`,
    byAccountNumber: (accountNumber: string) =>
      `/business-accounts/account-number/${accountNumber}`,
    create: "/business-accounts",
    update: (id: string) => `/business-accounts/byId/${id}`,
    updateBalance: (id: string) => `/business-accounts/byId/${id}/balance`,
    delete: (id: string) => `/business-accounts/byId/${id}`,
  },
  expenses: {
    list: "/expenses",
    byId: (id: string) => `/expenses/byId/${id}`,
    byCategory: (category: string) => `/expenses/byCategoryId/${category}`,
    byRecipient: (personId: string) => `/expenses/recipient/${personId}`,
    byDateRange: "/expenses/date-range",
    create: "/expenses",
    update: (id: string) => `/expenses/byId/${id}`,
    delete: (id: string) => `/expenses/byId/${id}`,
  },
  loans: {
    list: "/loans",
    byId: (id: string) => `/loans/byId/${id}`,
    byBorrower: (personId: string) => `/loans/borrower/${personId}`,
    byStatus: (status: string) => `/loans/byStatus/${status}`,
    create: "/loans",
    update: (id: string) => `/loans/byId/${id}`,
    // updateInstallment: (id: string, installmentNumber: string) =>
    //   `/loans/byId/${id}/installment/${installmentNumber}`,
    delete: (id: string) => `/loans/byId/${id}`,
  },
  salaries: {
    list: "/salaries",
    byId: (id: string) => `/salaries/byId/${id}`,
    byEmployee: (personId: string) => `/salaries/employee/${personId}`,
    byPeriod: (year: string, month: string) =>
      `/salaries/byPeriod/${year}/${month}`,
    byYear: (year: string) => `/salaries/byYear/${year}`,
    create: "/salaries",
    update: (id: string) => `/salaries/byId/${id}`,
    delete: (id: string) => `/salaries/byId/${id}`,
  },
};
