export const urls = {
  detailsByChassisNo: (chassisNo: string) => `/cars/${chassisNo}/details`,
  transactions: {
    list: "/transactions",
    byChassisNo: (chassisNo: string) => `/transactions/${chassisNo}`,
    create: "/transactions",
  },
  cheques: {
    list: "/cheques",
    byChassisNo: (chassisNo: string) => `/cheques/${chassisNo}`,
    unpaid: (chassisNo: string) => `/cheques/unpaid/${chassisNo}`,
    create: "/cheques",
  },
  investmentByChassis: (chassisNo: string) =>
    `/transactions/investment/${chassisNo}`,
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
  },
  settings: {
    list: "/settings",
  },
  // New API endpoints
  deals: {
    list: "/deals",
    byId: (id: string) => `/deals/id/${id}`,
    byVin: (vin: string) => `/deals/vin/${vin}`,
    byVehicleId: (vehicleId: string) => `/deals/vehicle/${vehicleId}`,
    byPerson: (personId: string) => `/deals/person/${personId}`,
    byStatus: (status: string) => `/deals/status/${status}`,
    create: "/deals",
    update: (id: string) => `/deals/id/${id}`,
    delete: (id: string) => `/deals/id/${id}`,
    option: (dealId: string, optionId: string) =>
      `/deals/${dealId}/option/${optionId}`,
  },
  transactionsNew: {
    list: "/transactions",
    byId: (id: string) => `/transactions/id/${id}`,
    byDeal: (dealId: string) => `/transactions/deal/${dealId}`,
    byPerson: (personId: string) => `/transactions/person/${personId}`,
    byProvider: (providerId: string) => `/transactions/person/${providerId}`,
    byAccount: (accountId: string) => `/transactions/account/${accountId}`,
    byType: (type: string) => `/transactions/type/${type}`,
    byDateRange: "/transactions/date-range",
    create: "/transactions",
    update: (id: string) => `/transactions/id/${id}`,
    delete: (id: string) => `/transactions/id/${id}`,
  },
  chequesNew: {
    list: "/cheques",
    byVin: (vin: string) => `/cheques/vin/${vin}`,
    byId: (id: string) => `/cheques/id/${id}`,
    byDeal: (dealId: string) => `/cheques/deal/${dealId}`,
    byPerson: (personId: string) => `/cheques/person/${personId}`,
    byStatus: (status: string) => `/cheques/status/${status}`,
    unpaidByDeal: (dealId: string) => `/cheques/unpaid/deal/${dealId}`,
    create: "/cheques",
    update: (id: string) => `/cheques/id/${id}`,
    addAction: (id: string) => `/cheques/id/${id}/action`,
    delete: (id: string) => `/cheques/id/${id}`,
  },
  people: {
    list: "/people",
    byId: (id: string) => `/people/id/${id}`,
    byNationalId: (nationalId: string) => `/people/national-id/${nationalId}`,
    byRole: (role: string) => `/people/role/${role}`,
    search: (name: string) => `/people/search/${name}`,
    create: "/people",
    update: (id: string) => `/people/id/${id}`,
    updateWallet: (id: string) => `/people/id/${id}/wallet`,
    deleteWalletTransaction: (id: string) => `/people/id/${id}/wallet/delete`,
    delete: (id: string) => `/people/id/${id}`,
  },
  wallet: {
    updateWalletTransfer: "/wallet/update-wallet-transfer",
  },
  report:{
   generatePersonReport: "/exportToExcel/generate-person-report",
  },
  users: {
    list: "/users",
  },
  vehicles: {
    list: "/vehicles",
    byId: (id: string) => `/vehicles/id/${id}`,
    byVin: (vin: string) => `/vehicles/vin/${vin}`,
    create: "/vehicles",
    update: (id: string) => `/vehicles/id/${id}`,
    delete: (id: string) => `/vehicles/id/${id}`,
  },
  businessAccounts: {
    list: "/business-accounts",
    active: "/business-accounts/active",
    byId: (id: string) => `/business-accounts/id/${id}`,
    byAccountNumber: (accountNumber: string) =>
      `/business-accounts/account-number/${accountNumber}`,
    create: "/business-accounts",
    update: (id: string) => `/business-accounts/id/${id}`,
    updateBalance: (id: string) => `/business-accounts/id/${id}/balance`,
    delete: (id: string) => `/business-accounts/id/${id}`,
  },
  expenses: {
    list: "/expenses",
    byId: (id: string) => `/expenses/id/${id}`,
    byCategory: (category: string) => `/expenses/category/${category}`,
    byRecipient: (personId: string) => `/expenses/recipient/${personId}`,
    byDateRange: "/expenses/date-range",
    create: "/expenses",
    update: (id: string) => `/expenses/id/${id}`,
    delete: (id: string) => `/expenses/id/${id}`,
  },
  loans: {
    list: "/loans",
    byId: (id: string) => `/loans/id/${id}`,
    byBorrower: (personId: string) => `/loans/borrower/${personId}`,
    byStatus: (status: string) => `/loans/status/${status}`,
    create: "/loans",
    update: (id: string) => `/loans/id/${id}`,
    updateInstallment: (id: string, installmentNumber: string) =>
      `/loans/id/${id}/installment/${installmentNumber}`,
    delete: (id: string) => `/loans/id/${id}`,
  },
  salaries: {
    list: "/salaries",
    byId: (id: string) => `/salaries/id/${id}`,
    byEmployee: (personId: string) => `/salaries/employee/${personId}`,
    byPeriod: (year: string, month: string) =>
      `/salaries/period/${year}/${month}`,
    byYear: (year: string) => `/salaries/year/${year}`,
    create: "/salaries",
    update: (id: string) => `/salaries/id/${id}`,
    delete: (id: string) => `/salaries/id/${id}`,
  },
};
